@baseUrl = http://localhost:3333
@token = {{Authenticate.response.body.access_token}}

# @name CreateAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Marlon",
  "email": "marlon4@teste.com",
  "password": "123456"
}

###

# @name Authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "marlon4@teste.com",
  "password": "123456"
}

###

# @name CreateQuestion
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{token}}